server:
  port: 8087

spring:
  application:
    name: comment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/codesync_comment
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

services:
  auth: http://localhost:8081
  project: http://localhost:8082
  file: http://localhost:8083
  version: http://localhost:8085
  notification: http://localhost:8088

jwt:
  secret: mySuperSecretKey123

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
    com.codesync: DEBUG