server:
  port: 8087

spring:
  application:
    name: comment-service
  datasource:
    url: jdbc:mysql://localhost:3306/codecollab_comment?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: dhruvsh@97
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      exposed-headers: "*"

services:
  auth: http://localhost:8081
  project: http://localhost:8082
  file: http://localhost:8083
  version: http://localhost:8086
  notification: http://localhost:8091
  collab: http://localhost:8084

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
    com.codesync: DEBUG

app:
  jwt:
    secret: your-256-bit-secret-key-here-must-be-at-least-32-characters-long-for-security