server:
  port: 8085

spring:
  application:
    name: execution-service
  datasource:
    url: jdbc:mysql://localhost:3306/codecollab_execution?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: dhruvsh@97
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    com.codesync: DEBUG

app:
  jwt:
    secret: your-256-bit-secret-key-here-must-be-at-least-32-characters-long-for-security